Update error messages for conda package installations

diff --git a/images/py-rocket-geospatial-2/Dockerfile b/images/py-rocket-geospatial-2/Dockerfile
--- a/images/py-rocket-geospatial-2/Dockerfile
+++ b/images/py-rocket-geospatial-2/Dockerfile
@@ -15,11 +15,11 @@ RUN wget -qO- https://raw.githubusercontent.com/retorquere/zotero-deb/master/ins
 
 COPY . /tmp/
 # Update conda env sequentially to prevent hairy solve
-RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-core1.yml || (echo "install-conda-packages.sh failed" && exit 1)
-RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-core2.yml || (echo "install-conda-packages.sh failed" && exit 1)
-RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-geo.yml || (echo "install-conda-packages.sh failed" && exit 1)
-RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-viz.yml || (echo "install-conda-packages.sh failed" && exit 1)
-RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-qgis.yml || (echo "install-conda-packages.sh failed" && exit 1)
+RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-core1.yml || (echo "install env-core1 failed" && exit 1)
+RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-core2.yml || (echo "install env-core2 failed" && exit 1)
+RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-geo.yml || (echo "install env-geo failed" && exit 1)
+RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-viz.yml || (echo "install env-viz failed" && exit 1)
+RUN /pyrocket_scripts/install-conda-packages.sh /tmp/env-qgis.yml || (echo "install env-qgis failed" && exit 1)
 RUN /pyrocket_scripts/install-r-packages.sh /tmp/install.R || (echo "install-r-package.sh failed" && exit 1)
 RUN /pyrocket_scripts/install-apt-packages.sh /tmp/apt.txt || (echo "install-apt-packages.sh failed" && exit 1)
 RUN /pyrocket_scripts/install-desktop.sh /tmp/Desktop|| (echo "setup-desktop.sh failed" && exit 1)
