set up the 3 geospatial images

diff --git a/images/py-geospatial/Dockerfile b/images/py-geospatial/Dockerfile
--- a/images/py-geospatial/Dockerfile
+++ b/images/py-geospatial/Dockerfile
@@ -5,14 +5,14 @@ LABEL org.opencontainers.image.author="eli.holmes@noaa.gov"
 LABEL org.opencontainers.image.source=https://github.com/nmfs-opensci/container-images/py-rocket-2
 LABEL org.opencontainers.image.description="Geospatial Python (3.12)"
 LABEL org.opencontainers.image.licenses=Apache2.0
-LABEL org.opencontainers.image.version=2025.04.23
+LABEL org.opencontainers.image.version=2025.04.27
 
 ENV PROJ_LIB=/srv/conda/envs/notebook/share/proj
 
 USER root
 
 COPY . /tmp2/
-RUN /pyrocket_scripts/install-conda-packages.sh /tmp2/environment.yml || echo "install-conda-packages.sh failed" || true
+RUN /pyrocket_scripts/install-conda-packages.sh /tmp2/environment.yml || (echo "install-conda-packages.sh failed" >&2 && exit 1)
 RUN rm -rf /tmp2
 
 # Install tools for working with Google Cloud Buckets
diff --git a/images/py-rocket-geospatial/Dockerfile b/images/py-rocket-geospatial/Dockerfile
--- a/images/py-rocket-geospatial/Dockerfile
+++ b/images/py-rocket-geospatial/Dockerfile
@@ -1,18 +1,18 @@
-FROM ghcr.io/nmfs-opensci/container-images/py-geospatial:2025.04.23
+FROM ghcr.io/nmfs-opensci/container-images/py-geospatial:2025.04.27
 
 LABEL org.opencontainers.image.maintainers="eli.holmes@noaa.gov"
 LABEL org.opencontainers.image.author="eli.holmes@noaa.gov"
 LABEL org.opencontainers.image.source=https://github.com/nmfs-opensci/container-images
 LABEL org.opencontainers.image.description="Geospatial Python (3.12) and R (4.4.3) image"
 LABEL org.opencontainers.image.licenses=Apache2.0
-LABEL org.opencontainers.image.version=2025.04.24
+LABEL org.opencontainers.image.version=2025.04.27
 
 USER root
 
 COPY . /tmp2/
-RUN /pyrocket_scripts/install-r-packages.sh /tmp2/install.R || echo "install-r-package.sh failed" || true
+RUN /pyrocket_scripts/install-r-packages.sh /tmp2/install.R || (echo "install-r-package.sh failed" >&2 && exit 1)
 RUN rm -rf /tmp2
-RUN /pyrocket_scripts/install-geospatial-r.sh || echo "install-geospatial-r.sh failed" || true
+RUN /pyrocket_scripts/install-geospatial-r.sh || (echo "install-geospatial-r.sh failed" >&2 && exit 1)
 
 USER ${NB_USER}
 WORKDIR ${HOME}
