add py-geospatial and r-geospatial
these just have the geospatial in one language

diff --git a/images/py-geospatial/Dockerfile b/images/py-geospatial/Dockerfile
--- a/images/py-geospatial/Dockerfile
+++ b/images/py-geospatial/Dockerfile
@@ -1,10 +1,22 @@
-FROM openscapes/python:39dffde
+FROM ghcr.io/nmfs-opensci/py-rocket-base:2025.04.17
+
 LABEL org.opencontainers.image.maintainers="eli.holmes@noaa.gov"
-LABEL org.opencontainers.image.author="luiz.lopez@nasa.gov"
-LABEL org.opencontainers.image.source=https://github.com/NASA-Openscapes/corn/tree/main/ci
-LABEL org.opencontainers.image.description="NASA Openscapes Python image used in workshops"
+LABEL org.opencontainers.image.author="eli.holmes@noaa.gov"
+LABEL org.opencontainers.image.source=https://github.com/nmfs-opensci/container-images/py-rocket-2
+LABEL org.opencontainers.image.description="Geospatial Python (3.12)"
 LABEL org.opencontainers.image.licenses=Apache2.0
+LABEL org.opencontainers.image.version=2025.04.23
+
+ENV PROJ_LIB=/srv/conda/envs/notebook/share/proj
+
+USER root
+
+COPY . /tmp2/
+RUN /pyrocket_scripts/install-conda-packages.sh /tmp2/environment.yml || echo "install-conda-packages.sh failed" || true
+RUN rm -rf /tmp2
+
+# Install tools for working with Google Cloud Buckets
+RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && apt-get update -y && apt-get install google-cloud-cli -y
 
 USER ${NB_USER}
-
-RUN mamba install -c conda-forge -n notebook cmocean
+WORKDIR ${HOME}
