Update Dockerfile base image and version

diff --git a/draft_images/test/Dockerfile b/draft_images/test/Dockerfile
--- a/draft_images/test/Dockerfile
+++ b/draft_images/test/Dockerfile
@@ -1,11 +1,11 @@
-FROM ghcr.io/nmfs-opensci/py-rocket-base/test:330aa44
+FROM ghcr.io/nmfs-opensci/py-rocket-base:2025.04.26
 
 LABEL org.opencontainers.image.maintainers="eli.holmes@noaa.gov"
 LABEL org.opencontainers.image.author="eli.holmes@noaa.gov"
 LABEL org.opencontainers.image.source=https://github.com/nmfs-opensci/container-images/py-rocket-2
 LABEL org.opencontainers.image.description="Geospatial Python (3.12) and R (4.4.3) image with Desktop (QGIS, Panoply, CWUtils)"
 LABEL org.opencontainers.image.licenses=Apache2.0
-LABEL org.opencontainers.image.version=2025.04.24
+LABEL org.opencontainers.image.version=2025.04.26
 
 ENV PROJ_LIB=/srv/conda/envs/notebook/share/proj
 
@@ -14,13 +14,23 @@ USER root
 RUN wget -qO- https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh | bash
 
 COPY . /tmp2/
-RUN /pyrocket_scripts/install-conda-packages.sh /tmp2/environment.yml || (echo "install-conda-packages.sh failed" >&2 && exit 1)
-RUN /pyrocket_scripts/install-r-packages.sh /tmp2/install.R || (echo "install-r-packages.sh failed" >&2 && exit 1)
-RUN /pyrocket_scripts/install-apt-packages.sh /tmp2/apt.txt || (echo "nstall-apt-packages.sh failed" >&2 && exit 1)
-RUN /pyrocket_scripts/install-desktop.sh /tmp2/Desktop || (echo "install-desktop.sh failed" >&2 && exit 1)
+RUN /pyrocket_scripts/install-conda-packages.sh /tmp2/environment.yml || echo "install-conda-packages.sh failed" || true
+RUN /pyrocket_scripts/install-r-packages.sh /tmp2/install.R || echo "install-r-package.sh failed" || true
+RUN /pyrocket_scripts/install-apt-packages.sh /tmp2/apt.txt || echo "install-apt-packages.sh failed" || true
+RUN /pyrocket_scripts/install-desktop.sh /tmp2/Desktop|| echo "setup-desktop.sh failed" || true
 RUN rm -rf /tmp2
-RUN /pyrocket_scripts/install-geospatial-r.sh || (echo "install-geospatial-r.sh failed" >&2 && exit 1)
 
+USER root
+# install the geospatial libraries and R spatial; the rocket script are part of py-rocket-base
+# need to ensure that it installs to the site-library (that user can control) and with a clean PATH
+# Ensure packages go to site-library whether installed via R, Rscript, or littler (r)
+RUN echo '.libPaths("/usr/local/lib/R/site-library")' > /etc/littler.r && \
+    echo '.libPaths("/usr/local/lib/R/site-library")' > /tmp/rprofile.site && \
+    R_PROFILE=/tmp/rprofile.site \
+    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
+    /rocker_scripts/install_geospatial.sh && \
+    rm /etc/littler.r /tmp/rprofile.site
+  
 # Install cwutils
 RUN cd /tmp && \
     wget https://www.star.nesdis.noaa.gov/socd/coastwatch/cwf/cwutils-4_0_0_198-linux-x86_64.tar.gz && \
@@ -32,9 +42,9 @@ ENV INSTALL4J ADD VM PARAMS=-Dsun.java2d.uiScale=2.0
 
 # Install panoply
 RUN cd /tmp && \
-  wget --user-agent="Mozilla/5.0" https://www.giss.nasa.gov/tools/panoply/download/PanoplyJ-5.6.0.tgz && \
-  tar -zxf PanoplyJ-5.6.0.tgz && \
-  rm -rf PanoplyJ-5.6.0.tgz
+  wget --user-agent="Mozilla/5.0" https://www.giss.nasa.gov/tools/panoply/download/PanoplyJ-5.7.1.tgz && \
+  tar -zxf PanoplyJ-5.7.1.tgz && \
+  rm -rf PanoplyJ-5.7.1.tgz
 ENV PATH=${PATH}:/tmp/PanoplyJ
 
 # Install tools for working with Google Cloud Buckets
