Update Dockerfile

diff --git a/draft_images/test/Dockerfile b/draft_images/test/Dockerfile
--- a/draft_images/test/Dockerfile
+++ b/draft_images/test/Dockerfile
@@ -3,14 +3,15 @@ FROM ghcr.io/nmfs-opensci/py-rocket-base:afad8e0f65e1
 RUN echo ${PATH}
 
 USER root
-RUN echo ${PATH}
-RUN /pyrocket_scripts/install-conda-packages.sh environment.yml || echo "install-conda-packages.sh failed" || true
-RUN /pyrocket_scripts/install-r-packages.sh install.R || echo "install-r-package.sh failed" || true
-RUN /pyrocket_scripts/install-pip-packages.sh requirements.txt || echo "install-pip-packages.sh failed" || true
-RUN /pyrocket_scripts/install-apt-packages.sh apt.txt || echo "install-apt-packages.sh failed" || true
+COPY . /tmp2/
+RUN /pyrocket_scripts/install-conda-packages.sh /tmp/environment.yml || echo "install-conda-packages.sh failed" || true
+RUN /pyrocket_scripts/install-r-packages.sh /tmp/install.R || echo "install-r-package.sh failed" || true
+RUN /pyrocket_scripts/install-pip-packages.sh /tmp/requirements.txt || echo "install-pip-packages.sh failed" || true
+RUN /pyrocket_scripts/install-apt-packages.sh /tmp/apt.txt || echo "install-apt-packages.sh failed" || true
 RUN /pyrocket_scripts/install-desktop.sh || echo "setup-desktop.sh failed" || true
 RUN /pyrocket_scripts/run-postbuild.sh || echo "run-postbuild.sh failed" || true
 RUN /pyrocket_scripts/setup-start.sh || echo "setup-start.sh failed" || true
+RUN rm -rf /tmp2
 USER ${NB_USER}
 
 USER root
